baseURL = "https://NikolajMeineche.github.io/CSS_website/"
title = "Unravelling Hogwarts Ties"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Magnus Harder", "Nikolaj Meineche", "Rebekka Madsen"]
    notebook = "/explainer_notebook.html"
    data = "https://github.com/Magnus-Harder/CSS_Project/tree/main/Data"
    github = "https://github.com/MagnusHarder/CSS_Project"
    [[params.nav]]
        label = "Data Analysis"
        link = "/data-analysis"
    [[params.nav]]
        label = "Temporal Analysis"
        link = "/temporal-analysis"
    [[params.nav]]
        label = "Muggles and Wizards"
        link = "/mvw"
    [[params.nav]]
        label = "Dumbledore's Army"
        link = "/da"
    [[params.nav]]
        label = "Snape's Allegiance"
        link = "/sa"


