baseURL = "https://NikolajMeineche.github.io/CSS_Website"
title = "Unravelling Hogwarts Ties"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Magnus Harder", "Nikolaj Meineche", "Rebekka Madsen"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/MagnusHarder/CSS_project"
    [[params.nav]]
        label = "Data Analysis"
        link = "/data-analysis"
    [[params.nav]]
        label = "Temporal Analysis"
        link = "/temporal-analysis"
    [[params.nav]]
        label = "Muggles VS Wizards"
        link = "/mvw"
    [[params.nav]]
        label = "Dumbledore's Army"
        link = "/da"
    [[params.nav]]
        label = "Snape's Allegiance"
        link = "/sa"
    [[params.nav]]
        label = "Black & Pettigrew"
        link = "/bp"

